import { ConflictDetected, InvariantViolation, ProtocolViolation } from "./errors.js";
import type { AgentId, FieldOwnership, Invariant, JsonObject, LinkId, LinkLifecycle, LinkMetrics, Revision, TurnMode } from "./types.js";
import { deepClone, linkId, mergeJson } from "./utils.js";
export interface LinkProtocolSpec { id?:LinkId; left:AgentId; right:AgentId; state?:JsonObject; fieldOwnership?:Record<string,FieldOwnership>; mode?:TurnMode; turnOwner?:"left"|"right"; invariants?:Invariant<LinkSnapshot>[]; strength?:number; decayRate?:number; }
export interface LinkSnapshot { id:LinkId; left:AgentId; right:AgentId; state:JsonObject; fieldOwnership:Record<string,FieldOwnership>; mode:TurnMode; turnOwner:"left"|"right"; lifecycle:LinkLifecycle; revisions:Revision[]; metrics:LinkMetrics; strength:number; decayRate:number; createdAt:number; updatedAt:number; }
export interface MutationProposal { author:AgentId; delta:JsonObject; evidence?:string[]; informationGain?:number; utility?:number; communicationCost?:number; }
export class LinkProtocol {
 #s:LinkSnapshot; #invariants:Invariant<LinkSnapshot>[];
 constructor(spec:LinkProtocolSpec){const now=Date.now();this.#s={id:spec.id??linkId(),left:spec.left,right:spec.right,state:deepClone(spec.state??{}),fieldOwnership:{...(spec.fieldOwnership??{})},mode:spec.mode??"strict_alternation",turnOwner:spec.turnOwner??"left",lifecycle:"candidate",revisions:[],metrics:{activations:0,usefulUpdates:0,informationGain:0,utility:0,reliability:1,communicationCost:0,errorRate:0,synchronizationQuality:1},strength:spec.strength??0.1,decayRate:spec.decayRate??0.000001,createdAt:now,updatedAt:now};this.#invariants=[...(spec.invariants??[])];this.#validate(this.#s);}
 get id():LinkId{return this.#s.id;} snapshot():LinkSnapshot{return deepClone(this.#s);} activate(){this.#s.lifecycle="active";this.#s.metrics.activations++;this.#s.metrics.lastActivatedAt=Date.now();this.#s.updatedAt=Date.now();} sleep(){this.#s.lifecycle="dormant";this.#s.updatedAt=Date.now();} retire(){this.#s.lifecycle="retired";this.#s.updatedAt=Date.now();}
 mutate(proposal:MutationProposal):Revision{this.#assertParticipant(proposal.author);this.#assertTurn(proposal.author);this.#assertFieldOwnership(proposal.author,proposal.delta);const nextState=mergeJson(this.#s.state,proposal.delta);const side=this.sideOf(proposal.author);const nextTurn=this.#s.mode==="strict_alternation"?(side==="left"?"right":"left"):this.#s.turnOwner;const revision:Revision={id:this.#s.revisions.length+1,author:proposal.author,parent:this.#s.revisions.at(-1)?.id??null,timestamp:Date.now(),delta:deepClone(proposal.delta),evidence:[...(proposal.evidence??[])],kind:"state"};const next:LinkSnapshot={...this.#s,state:nextState,turnOwner:nextTurn,revisions:[...this.#s.revisions,revision],updatedAt:revision.timestamp,metrics:{...this.#s.metrics,usefulUpdates:this.#s.metrics.usefulUpdates+(Object.keys(proposal.delta).length>0?1:0),informationGain:this.#s.metrics.informationGain+(proposal.informationGain??0),utility:this.#s.metrics.utility+(proposal.utility??0),communicationCost:this.#s.metrics.communicationCost+(proposal.communicationCost??0)}};this.#validate(next);this.#s=next;this.recalculateStrength();return revision;}
 mutateProtocol(author:AgentId,patch:{mode?:TurnMode;fieldOwnership?:Record<string,FieldOwnership>;decayRate?:number},evidence:string[]=[]):Revision{this.#assertParticipant(author);this.#assertTurn(author);const revision:Revision={id:this.#s.revisions.length+1,author,parent:this.#s.revisions.at(-1)?.id??null,timestamp:Date.now(),delta:patch as unknown as JsonObject,evidence,kind:"protocol"};const side=this.sideOf(author);const next:LinkSnapshot={...this.#s,...(patch.mode?{mode:patch.mode}:{}),...(patch.fieldOwnership?{fieldOwnership:{...this.#s.fieldOwnership,...patch.fieldOwnership}}:{}),...(patch.decayRate===undefined?{}:{decayRate:patch.decayRate}),revisions:[...this.#s.revisions,revision],turnOwner:this.#s.mode==="strict_alternation"?(side==="left"?"right":"left"):this.#s.turnOwner,updatedAt:revision.timestamp};this.#validate(next);this.#s=next;return revision;}
 recordFailure(){const m=this.#s.metrics;const errors=m.errorRate*Math.max(1,m.activations)+1;this.#s.metrics={...m,errorRate:errors/Math.max(1,m.activations+1),reliability:Math.max(0,m.reliability*0.9),synchronizationQuality:Math.max(0,m.synchronizationQuality*0.9)};this.recalculateStrength();}
 addContradiction(author:AgentId,proposition:string,left:unknown,right:unknown):Revision{this.#s.lifecycle="conflicted";return this.mutate({author,delta:{contradictions:{[proposition]:{left,right,status:"unresolved"} as never}},evidence:["contradiction-detected"]});}
 resolveContradiction(author:AgentId,proposition:string,resolution:unknown,evidence:string[]):Revision{const rev=this.mutate({author,delta:{resolutions:{[proposition]:resolution as never}},evidence});this.#s.lifecycle="active";return rev;}
 decay(now=Date.now()):number{const last=this.#s.metrics.lastActivatedAt??this.#s.createdAt;const dt=Math.max(0,now-last);this.#s.strength*=Math.exp(-this.#s.decayRate*dt);if(this.#s.strength<0.01&&this.#s.lifecycle==="active")this.#s.lifecycle="weakening";if(this.#s.strength<0.001)this.#s.lifecycle="dormant";return this.#s.strength;}
 recalculateStrength():number{const m=this.#s.metrics;const f=Math.log1p(m.activations);const useful=m.activations===0?0:m.usefulUpdates/m.activations;const raw=0.10*f+0.20*useful+0.20*normalized(m.informationGain)+0.15*normalized(m.utility)+0.15*m.reliability+0.15*m.synchronizationQuality-0.10*normalized(m.communicationCost)-0.15*m.errorRate;this.#s.strength=clamp01(raw);return this.#s.strength;}
 sideOf(agent:AgentId):"left"|"right"{if(agent===this.#s.left)return"left";if(agent===this.#s.right)return"right";throw new ProtocolViolation(`${agent} is not a participant of ${this.id}`);} other(agent:AgentId):AgentId{return this.sideOf(agent)==="left"?this.#s.right:this.#s.left;}
 #assertParticipant(agent:AgentId){this.sideOf(agent);} #assertTurn(agent:AgentId){if(this.#s.mode!=="strict_alternation")return;if(this.sideOf(agent)!==this.#s.turnOwner)throw new ProtocolViolation(`not ${agent}'s turn on ${this.id}`);} #assertFieldOwnership(author:AgentId,delta:JsonObject){const side=this.sideOf(author);for(const field of Object.keys(delta)){const ownership=this.#s.fieldOwnership[field]??"either";if(ownership==="runtime")throw new ProtocolViolation(`${field} is runtime-owned`);if(ownership==="shared_consensus")throw new ConflictDetected(`${field} requires consensus mutation`);if(ownership!=="either"&&ownership!==side)throw new ProtocolViolation(`${side} cannot write ${field}; owner=${ownership}`);}}
 #validate(value:LinkSnapshot){if(value.left===value.right)throw new InvariantViolation("link participants must be distinct");if(value.strength<0||value.strength>1)throw new InvariantViolation("strength must be in [0,1]");if(value.decayRate<0)throw new InvariantViolation("decayRate cannot be negative");for(const inv of this.#invariants)if(!inv.check(value))throw new InvariantViolation(`Link invariant failed: ${inv.id}: ${inv.description}`);}
}
function clamp01(x:number){return Math.max(0,Math.min(1,Number.isFinite(x)?x:0));} function normalized(x:number){return x<=0?0:x/(1+x);}
