import { BudgetViolation, InvariantViolation, PermissionViolation } from "./errors.js";
import type { AgentId, AgentLifecycle, Belief, Budget, Capability, Commitment, Invariant, JsonObject, LinkId, ObjectiveVector } from "./types.js";
import { agentId, assertConfidence, deepClone, mergeJson } from "./utils.js";
export interface NanoAgentSpec { id?: AgentId; generation?: number; lineage?: AgentId[]; objective: ObjectiveVector; capabilities?: Capability[]; privateState?: JsonObject; exposedState?: JsonObject; durableState?: JsonObject; ephemeralState?: JsonObject; beliefs?: Belief[]; permissions?: string[]; budget?: Partial<Budget>; invariants?: Invariant<NanoAgentSnapshot>[]; ttlMs?: number; }
export interface NanoAgentSnapshot { id: AgentId; generation: number; lineage: AgentId[]; objective: ObjectiveVector; lifecycle: AgentLifecycle; capabilities: Capability[]; privateState: JsonObject; exposedState: JsonObject; durableState: JsonObject; ephemeralState: JsonObject; beliefs: Belief[]; commitments: Commitment[]; permissions: string[]; budget: Budget; links: LinkId[]; createdAt: number; updatedAt: number; ttlMs?: number; }
const DEFAULT_BUDGET: Budget = { compute: Infinity, tokens: Infinity, money: Infinity, latencyMs: Infinity, externalActions: Infinity };
export class NanoAgent {
  #s: NanoAgentSnapshot; #invariants: Invariant<NanoAgentSnapshot>[];
  constructor(spec: NanoAgentSpec) { const now=Date.now(); this.#s={id:spec.id??agentId(),generation:spec.generation??0,lineage:[...(spec.lineage??[])],objective:deepClone(spec.objective),lifecycle:"created",capabilities:deepClone(spec.capabilities??[]),privateState:deepClone(spec.privateState??{}),exposedState:deepClone(spec.exposedState??{}),durableState:deepClone(spec.durableState??{}),ephemeralState:deepClone(spec.ephemeralState??{}),beliefs:deepClone(spec.beliefs??[]),commitments:[],permissions:[...(spec.permissions??[])],budget:{...DEFAULT_BUDGET,...(spec.budget??{})},links:[],createdAt:now,updatedAt:now,...(spec.ttlMs===undefined?{}:{ttlMs:spec.ttlMs})}; this.#invariants=[...(spec.invariants??[])]; this.#validate(this.#s); }
  get id(): AgentId{return this.#s.id;} get lifecycle():AgentLifecycle{return this.#s.lifecycle;} snapshot():NanoAgentSnapshot{return deepClone(this.#s);}
  activate(){this.#transition("active");} sleep(){this.#transition("dormant");} retire(){this.#transition("retired");} quarantine(){this.#transition("quarantined");}
  expose(delta:JsonObject){this.#mutate({exposedState:mergeJson(this.#s.exposedState,delta)});} remember(delta:JsonObject){this.#mutate({durableState:mergeJson(this.#s.durableState,delta)});} think(delta:JsonObject){this.#mutate({privateState:mergeJson(this.#s.privateState,delta)});} setEphemeral(delta:JsonObject){this.#mutate({ephemeralState:mergeJson(this.#s.ephemeralState,delta)});}
  setBelief(belief:Belief){assertConfidence(belief.confidence);const beliefs=this.#s.beliefs.filter(b=>b.proposition!==belief.proposition);beliefs.push(deepClone(belief));this.#mutate({beliefs});}
  addLink(id:LinkId){if(!this.#s.links.includes(id))this.#mutate({links:[...this.#s.links,id]});} removeLink(id:LinkId){this.#mutate({links:this.#s.links.filter(x=>x!==id)});} addCommitment(c:Commitment){this.#mutate({commitments:[...this.#s.commitments,deepClone(c)]});}
  requirePermission(permission:string){if(!this.#s.permissions.includes(permission))throw new PermissionViolation(`${this.id} lacks ${permission}`);} consumeBudget(kind:keyof Budget,amount:number){if(amount<0)throw new BudgetViolation("budget consumption cannot be negative");const current=this.#s.budget[kind];if(current<amount)throw new BudgetViolation(`${this.id} exhausted ${kind}`);this.#mutate({budget:{...this.#s.budget,[kind]:current-amount}});}
  clone(overrides:Partial<NanoAgentSpec>={}):NanoAgent{return new NanoAgent({objective:overrides.objective??this.#s.objective,capabilities:overrides.capabilities??this.#s.capabilities,privateState:overrides.privateState??this.#s.privateState,exposedState:overrides.exposedState??this.#s.exposedState,durableState:overrides.durableState??this.#s.durableState,ephemeralState:overrides.ephemeralState??{},beliefs:overrides.beliefs??this.#s.beliefs,permissions:overrides.permissions??this.#s.permissions,budget:overrides.budget??this.#s.budget,generation:this.#s.generation+1,lineage:[...this.#s.lineage,this.#s.id],...(overrides.ttlMs===undefined?{}:{ttlMs:overrides.ttlMs})});}
  split(objectives:ObjectiveVector[]):NanoAgent[]{if(objectives.length<2)throw new Error("split requires at least two objectives");return objectives.map(objective=>this.clone({objective}));}
  static merge(a:NanoAgent,b:NanoAgent,objective:ObjectiveVector):NanoAgent{const as=a.snapshot(),bs=b.snapshot();return new NanoAgent({objective,capabilities:uniqueById([...as.capabilities,...bs.capabilities]),exposedState:mergeJson(as.exposedState,bs.exposedState),durableState:mergeJson(as.durableState,bs.durableState),beliefs:dedupeBeliefs([...as.beliefs,...bs.beliefs]),permissions:[...new Set([...as.permissions,...bs.permissions])],budget:{compute:as.budget.compute+bs.budget.compute,tokens:as.budget.tokens+bs.budget.tokens,money:as.budget.money+bs.budget.money,latencyMs:Math.max(as.budget.latencyMs,bs.budget.latencyMs),externalActions:as.budget.externalActions+bs.budget.externalActions},generation:Math.max(as.generation,bs.generation)+1,lineage:[...new Set([...as.lineage,as.id,...bs.lineage,bs.id])]});}
  #transition(lifecycle:AgentLifecycle){this.#mutate({lifecycle});} #mutate(patch:Partial<NanoAgentSnapshot>){const next={...this.#s,...deepClone(patch),updatedAt:Date.now()};this.#validate(next);this.#s=next;} #validate(value:NanoAgentSnapshot){for(const inv of this.#invariants)if(!inv.check(value))throw new InvariantViolation(`NanoAgent invariant failed: ${inv.id}: ${inv.description}`);}
}
function uniqueById(values:Capability[]):Capability[]{return [...new Map(values.map(x=>[x.id,x])).values()];}
function dedupeBeliefs(values:Belief[]):Belief[]{const map=new Map<string,Belief>();for(const belief of values){const current=map.get(belief.proposition);if(!current||belief.confidence>=current.confidence)map.set(belief.proposition,belief);}return [...map.values()];}
